apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wsi-eks-cluster
  region: ap-northeast-2
  version: "1.29"
  tags:
    karpenter.sh/discovery: wsi-eks-cluster
iam:
  withOIDC: true
  podIdentityAssociations:
    - namespace: "karpenter"
      serviceAccountName: karpenter
      roleName: wsi-eks-cluster-karpenter
      permissionPolicyARNs:
        - arn:aws:iam::690677342176:policy/KarpenterControllerPolicy-wsi-eks-cluster

iamIdentityMappings:
  - arn: "arn:aws:iam::690677342176:role/KarpenterNodeRole-wsi-eks-cluster"
    username: system:node:{{EC2PrivateDNSName}}
    groups:
      - system:bootstrappers
      - system:nodes

vpc:
  subnets:
    private:
      ap-northeast-2a:
        id: subnet-01b61063e3e6b73d4
      ap-northeast-2b:
        id: subnet-0804e6358c9aa5ac8

managedNodeGroups:
  - name: wsi-app-ng
    minSize: 2
    desiredCapacity: 2
    maxSize: 10
    maxPodsPerNode: 7
    instanceType: t3.micro
    instanceName: wsi-app-node
    privateNetworking: true
    iam:
      withAddonPolicies:
        imageBuilder: true
        autoScaler: true
        externalDNS: true
        certManager: true
        appMesh: true
        appMeshPreview: true
        ebs: true
        fsx: true
        efs: true
        awsLoadBalancerController: true
        xRay: true
        cloudWatch: true

cloudWatch:
  clusterLogging:
    enableTypes: ["*"]

addons:
  - name: eks-pod-identity-agent
